<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FieldOps.Modules.Accounts.Core\FieldOps.Modules.Accounts.Core.csproj" />
	</ItemGroup>

</Project>
