<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FieldOps.Shared.Infrastructure\FieldOps.Shared.Infrastructure.csproj" />
	  <ProjectReference Include="..\FieldOps.Modules.Files.Contracts\FieldOps.Modules.Files.Contracts.csproj" />

  </ItemGroup>

</Project>
