<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\FieldOps.Modules.Accounts.Api\FieldOps.Modules.Accounts.Api.csproj" />
	  <ProjectReference Include="..\FieldOps.Modules.Files.Api\FieldOps.Modules.Files.Api.csproj" />
	  <ProjectReference Include="..\FieldOps.Modules.Jobs.Api\FieldOps.Modules.Jobs.Api.csproj" />
	  <ProjectReference Include="..\FieldOps.Modules.Reports.Api\FieldOps.Modules.Reports.Api.csproj" />
	  <ProjectReference Include="..\FieldOps.Modules.Operators.Api\FieldOps.Modules.Operators.Api.csproj" />
	  <ProjectReference Include="..\FieldOps.Modules.Technicians.Api\FieldOps.Modules.Technicians.Api.csproj" />
	  <ProjectReference Include="..\FieldOps.Shared.Infrastructure\FieldOps.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
