<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FieldOps.Modules.Accounts.Contracts\FieldOps.Modules.Accounts.Contracts.csproj" />
    <ProjectReference Include="..\FieldOps.Shared.Infrastructure\FieldOps.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
